COLLECTION_NAMES = {
    "A": "Alienation Office",
    "AB": "UK Atomic Energy Authority",
    "ACE": "Records of the Arts Council England",
    "ACT": "Government Actuary's Department",
    "ADM": "Admiralty, Navy, Royal Marines, and Coastguard",
    "AE": "Royal Commission on Historical Monuments (England)",
    "AF": "Parliamentary Boundary Commissions for England and Wales",
    "AH": "Location of Offices Bureau",
    "AHDB": "Agriculture and Horticulture Development Board",
    "AIR": "Air Ministry and Royal Air Force records",
    "AJ": "Consumer Council",
    "AK": "County Courts",
    "AM": "Parliamentary Counsel's Office",
    "AN": "British Transport Commission and the British Railways Board",
    "AO": "National Audit Office and predecessors",
    "AP": "Irish Sailors and Soldiers Land Trust",
    "AR": "The Wallace Collection",
    "ASI": "Inquiry into allegations of human rights abuse of Iraqi nationals by British troops in the aftermath of the'battle of Danny Boy' (The Al-Sweady Inquiry)",
    "ASSI": "Justices of Assize, Gaol Delivery, Oyer and Terminer, and Nisi Prius",
    "AST": "Unemployment Assistance Boards",
    "AT": "Various departments for environment, transport, communities, and local government",
    "AVIA": "Ministry of Aviation",
    "AW": "British European Airways and British Overseas Airways Corporation",
    "AX": "Local Government Boundary Commission for England",
    "AY": "Various Research Institutes and Councils",
    "B": "Bankruptcy and debt relief courts",
    "BA": "Civil Service Department",
    "BC": "Law Commission",
    "BD": "Welsh Office",
    "BE": "Iron and Steel Corporation",
    "BF": "Pensions Appeal Tribunals",
    "BH": "Hudson's Bay Company Archives",
    "BIS": "Department for Business, Innovation and Skills",
    "BJ": "Meteorological Office",
    "BK": "National Dock Labour Corporation and National Dock Labour Board",
    "BL": "Council on Tribunals and successors",
    "BLK": "Business Link",
    "BM": "Disabled Persons Employment Corporation Ltd and Remploy Ltd",
    "BN": "Department of Health and Social Security",
    "BP": "The Royal Fine Art Commission",
    "BPC": "British Potato Council",
    "BR": "British Transport Docks Board",
    "BS": "Records of defunct temporary bodies",
    "BT": "Board of Trade and successors",
    "BV": "Parole Board",
    "BW": "British Council",
    "BX": "Coal Industry Social Welfare Organisation",
    "BY": "National Portrait Gallery",
    "C": "Chancery, the Wardrobe, Royal Household, Exchequer and various commissions",
    "CA": "Countryside Agency and successors",
    "CAB": "Cabinet Office",
    "CABE": "Commission for Architecture and the Built Environment",
    "CAOG": "Crown Agents for Overseas Governments and Administrations",
    "CB": "National Playing Fields Association",
    "CCW": "Consumer Council for Water",
    "CD": "Cinematograph films",
    "CE": "British Museum",
    "CEF": "Centre for Environment, Fisheries and Aquaculture Science (Cefas)",
    "CES": "UK Commission for Employment and Skills and related bodies",
    "CF": "National Health Service hospitals",
    "CHAR": "Charity Commissioners and Charity Commission",
    "CHES": "Palatinate of Chester, including the county of Flint",
    "CJ": "Northern Ireland Office",
    "CK": "Commission for Racial Equality and predecessors",
    "CL": "Certification Office for Trade Unions and Employers' Associations",
    "CLG": "Department of Communities and Local Government",
    "CM": "Property Services Agency",
    "CN": "Photographic prints and negatives extracted from various record series",
    "CO": "Colonial Office, Commonwealth and Foreign and Commonwealth Offices",
    "COAL": "National Coal Board and predecessors, and related bodies",
    "COPY": "Copyright Office and Stationers' Company",
    "COU": "National Parks Commission and the Countryside Commission",
    "CP": "Court of Common Pleas",
    "CPS": "Crown Prosecution Service",
    "CRES": "The Crown Estate and predecessors",
    "CRIM": "Central Criminal Court",
    "CSC": "Civil Service Commission",
    "CSPR": "Civil Service Pay Research Unit",
    "CT": "National Insurance Commissioners and the Social Security Commissioners",
    "CUST": "Boards of Customs, Excise, and Customs and Excise, and HM Revenue and Customs",
    "CV": "Value Added Tax Tribunals",
    "CW": "Advisory, Conciliation and Arbitration Service",
    "CWG": "Commonwealth War Graves Commission",
    "CX": "Price Commission",
    "CY": "Royal Commission on Environmental Pollution",
    "D": "Rural Development Commission and predecessors",
    "DB": "Council for National Academic Awards",
    "DC": "London Museum",
    "DD": "Local Government Boundary Commission for Wales",
    "DEFE": "Ministry of Defence",
    "DEL": "High Court of Delegates",
    "DF": "Natural History Museum",
    "DFT": "Department for Transport",
    "DG": "International Organisations",
    "DGOV": "Directgov",
    "DH": "Records of the British Library and the British Museum Library",
    "DJ": "Post Office Users' National Council",
    "DK": "National Ports Council",
    "DL": "Duchy of Lancaster",
    "DM": "Occupational Pensions Board",
    "DN": "Public Health Laboratory Service Board",
    "DO": "Dominions Office, and Commonwealth Relations and Foreign and Commonwealth Offices",
    "DPP": "Director of Public Prosecutions",
    "DR": "Civil Aviation Authority",
    "DSA": "Driving Standards Agency",
    "DSIR": "Department of Scientific and Industrial Research",
    "DT": "General Nursing Council for England and Wales",
    "DURH": "Palatinate of Durham",
    "DV": "Central Midwives Board",
    "DVLA": "Driver and Vehicle Licensing Agency",
    "DW": "Council for the Training of Health Visitors",
    "DX": "Panel of Assessors for District Nurse Training",
    "DY": "Joint Board of Clinical Nursing Studies",
    "E": "Exchequer, Office of First Fruits and Tenths, and the Court of Augmentations",
    "EA": "National Council, and Council, for Educational Technology",
    "EB": "Commission on Museums and Galleries",
    "EC": "Electoral Commission",
    "ECCL": "Ecclesiastical Commission",
    "ECG": "Export Credit Guarantee Department",
    "ED": "Department of Education and Science",
    "EF": "Health and Safety Commission and Executive",
    "EG": "Department of Energy",
    "EH": "Pay Board",
    "EJ": "Schools Council for Curriculum and Examinations",
    "EL": "Council for the Encouragement of Music and the Arts and Arts Council of Great Britain",
    "EM": "Special Commissioners of Income Tax",
    "EN": "Imperial War Museum",
    "EP": "Reviewing Committee on the Export of Works of Art",
    "ER": "Standing Civilian Courts",
    "ES": "Atomic Weapons Establishment",
    "ET": "Manpower Services Commission",
    "EV": "Science and Engineering Research Council",
    "EW": "Department of Economic Affairs",
    "EXT": "Documents and objects extracted from various record series",
    "EY": "Social Science Research Council",
    "F": "Forestry Commission",
    "FA": "Office of Gas Supply (OFGAS)",
    "FB": "Central Bureau for Educational Visits and Exchanges",
    "FCO": "Foreign and Commonwealth Office and predecessors",
    "FD": "Medical Research Council",
    "FEC": "Forfeited Estates Commission",
    "FERA": "Food and Environment Research Agency",
    "FG": "National Economic Development Council and National Economic Development Office",
    "FH": "National Bus Company",
    "FJ": "Commission for the New Towns",
    "FK": "Office of the Secretary of State for Local Government and Regional Planning",
    "FL": "Adult Literacy Resource Agency",
    "FM": "Historic Buildings and Monuments Commission for England (English Heritage)",
    "FN": "Pilotage Commission",
    "FO": "Foreign Office",
    "FP": "Health Education Council and Health Education Authority",
    "FR": "Legal Aid Board, the Legal Services Commission, and predecessors",
    "FS": "Registry of Friendly Societies",
    "FT": "Nature Conservancy, the Nature Conservancy Council and English Nature",
    "FV": "Department of Trade and Industry, 1970-1974",
    "FW": "National Curriculum Council",
    "FY": "Potato Marketing Boards",
    "GCDA": "Government Car and Despatch Agency",
    "GEO": "Government Equalities Office",
    "GFM": "Copies of captured records of the German, Italian and Japanese Governments.",
    "GIRO": "National Girobank and Predecessors",
    "GT": "General Teaching Council for England",
    "GUK": "Records of GOV.UK",
    "HA": "Natural Environment Research Council",
    "HB": "Office of Electricity Regulation",
    "HCA": "High Court of Admiralty and colonial Vice-Admiralty courts",
    "HD": "Secret Intelligence Service",
    "HE": "English National Board for Nursing, Midwifery and Health Visiting",
    "HF": "Ministry of Technology",
    "HK": "Museums Association",
    "HLG": "Ministry of Housing and Local Government",
    "HMC": "Royal Commission on Historical Manuscripts",
    "HN": "Central Computer and Telecommunications Agency",
    "HO": "Home Office",
    "HP": "National Radiological Protection Board",
    "HR": "Marshall Aid Commemoration Commission",
    "HS": "Special Operations Executive",
    "HT": "Commission for Local Administration in England",
    "HV": "Crown Estate Paving Commission",
    "HW": "Government Communications Headquarters (GCHQ)",
    "HWA": "Highways Agency",
    "HX": "Civil Service Occupational Health Service and Civil Service Occupational Health and Safety Agency",
    "HY": "Intervention Board for Agricultural Produce",
    "IBS": "Reserved for forthcoming transfer",
    "ILB": "Coroner's Inquests into the London Bombings of 7 July 2005",
    "IND": "Indexes to various series",
    "INF": "Central Office of Information",
    "IPSA": "Independent Parliamentary Standards Authority",
    "IR": "Boards of Stamps, Taxes, Excise, Stamps and Taxes, and Inland Revenue",
    "J": "Supreme Court of Judicature",
    "JA": "Department of Health",
    "JB": "Department for Work and Pensions",
    "JC": "Office of Water Services (Ofwat) and the Water Services Regulation Authority",
    "JD": "Monopolies and Mergers Commission",
    "JE": "Office of the National Lottery",
    "JF": "Department of Prices and Consumer Protection",
    "JH": "Ministry of Land and Natural Resources",
    "JK": "Office of Her Majesty's Chief Inspector of Schools in Wales",
    "JL": "Curriculum Council for Wales and the Curriculum and Assessment Authority for Wales",
    "JM": "Further Education and Higher Education Funding Councils for Wales",
    "JN": "Committee on Standards in Public Life and related bodies",
    "JP": "The Adjudicators Office",
    "JR": "Office of the Rail Regulator",
    "JS": "Further Education Funding Council for England",
    "JT": "Local Government Commission for England",
    "JUST": "Records of itinerant justices and other court records",
    "JV": "Milk Marketing Board",
    "JW": "Metrication Board",
    "JX": "Data Protection Registrar and Successors",
    "JY": "Civil Service College",
    "KA": "Office of Passenger Rail Franchising",
    "KB": "Court of King's Bench",
    "KC": "School Examinations and Assessment Council",
    "KD": "Coal Authority",
    "KE": "Royal Air Force Museum",
    "KF": "Inquiry into Exports of Defence Equipment to Iraq and Related Prosecutions (Scott Inquiry)",
    "KH": "Special Educational Needs Tribunal",
    "KJ": "Government Property Lawyers",
    "KL": "Funding Agency for Schools",
    "KM": "Food Standards Agency",
    "KN": "United Kingdom Central Council for Nursing, Midwifery and Health Visiting",
    "KP": "Advisory Committee on Legal Education and Conduct",
    "KR": "Joint Nature Conservation Committee",
    "KS": "Radiocommunications Agency",
    "KT": "Office for Standards in Education",
    "KV": "Security Service",
    "KW": "Royal Parks Agency",
    "KX": "Historic Royal Palaces Agency",
    "KY": "National Council for Vocational Qualifications",
    "LAB": "Departments responsible for labour and employment matters",
    "LAR": "Land Registry",
    "LB": "Combined Tax Tribunal",
    "LC": "Lord Chamberlain and other officers of the Royal Household",
    "LCO": "Lord Chancellor's Office",
    "LD": "Office of Fair Trading",
    "LE": "The Court Service and Successors",
    "LEO": "Lyons Inquiry into Local Government",
    "LEV": "Inquiry into the Culture, Practices and Ethics of the Press (Leveson Inquiry)",
    "LF": "Office of Telecommunications (Oftel)",
    "LH": "Women's National Commission",
    "LJ": "Council for the Central Laboratory of the Research Councils",
    "LK": "Police Complaints Authority and Police Complaints Board",
    "LM": "Department of Transport",
    "LN": "Building Societies Commission",
    "LO": "Law Officers' Department",
    "LOC": "London 2012 Organising Committee of the Olympic and Paralympic Games (LOCOG)",
    "LP": "Department of the Environment, Transport and the Regions",
    "LR": "Office of the Auditors of Land Revenue",
    "LRRO": "Land Revenue Records and Enrolments",
    "LS": "Lord Steward, the Board of Green Cloth",
    "LSIS": "Learning and Skills Improvement Service",
    "LT": "Lands Tribunal",
    "LV": "Friendly Societies Commission",
    "LX": "Contributions Agency",
    "LY": "Child Maintenance and Enforcement Commission",
    "MAF": "Agriculture, Fisheries and Food Departments",
    "MCA": "Maritime and Coastguard Agency",
    "MEPO": "Metropolitan Police Office",
    "MF": "Maps and plans extracted to flat storage from various departments",
    "MFC": "Maps and plans extracted to flat storage from various departments formerly held at the Public Record Office, Chancery Lane",
    "MH": "Ministry of Health",
    "MFQ": "Maps and plans extracted to flat storage from various departments held at the Public Record Office, Kew",
    "MHRA": "Medicines and Healthcare Products Regulatory Agency",
    "MINT": "Royal Mint",
    "MJ": "Ministry of Justice",
    "MM": "Millennium Commission",
    "MONW": "Royal Commission on Ancient and Historical Monuments in Wales and Monmouthshire",
    "MPA": "Chancery: maps and plans extracted to flat storage",
    "MPAA": "Chancery: maps and plans extracted to extra large flat storage",
    "MPB": "Exchequer: maps and plans extracted to flat storage",
    "MPBB": "Exchequer: maps and plans extracted to extra large flat storage",
    "MPC": "Duchy of Lancaster: maps and plans extracted to flat storage",
    "MPCC": "Duchy of Lancaster: maps and plans extracted to extra large flat storage",
    "MPD": "Treasury: maps and plans extracted to flat storage",
    "MPDD": "Treasury: maps and plans extracted to extra large flat storage",
    "MPE": "Land Revenue Records and Enrolments: maps and plans extracted to flat storage",
    "MPEE": "Land Revenue Records and Enrolments: maps and plans extracted to extra large flat storage",
    "MPF": "State Paper Office: maps and plans extracted to flat storage",
    "MPFF": "State Paper Office: maps and plans extracted to extra large flat storage",
    "MPG": "Colonial Office: maps and plans extracted to flat storage",
    "MPGG": "Colonial Office: maps and plans extracted to extra large flat storage",
    "MPH": "War Office: maps and plans extracted to flat storage",
    "MPHH": "War Office: maps and plans extracted to extra large flat storage",
    "MPI": "Maps and plans extracted to flat storage from records of departments not assigned an individual map extract prefix",
    "MPII": "Maps and plans extracted to extra large flat storage from records of departments not assigned an individual map prefix",
    "MPK": "Foreign Office: maps and plans extracted to flat storage",
    "MPKK": "Foreign Office: maps and plans extracted to extra large flat storage",
    "MPL": "Court of Common Pleas: maps and plans extracted to flat storage",
    "MPLL": "Court of Common Pleas: maps and plans extracted to extra large flat storage",
    "MPM": "Flat maps and drawings of special interest",
    "MPN": "Court of King's Bench: maps and plans extracted to flat storage",
    "MPNN": "Court of King's Bench: maps and plans extracted to extra large flat storage",
    "MPO": "Forestry Commission maps and plans",
    "MPP": "Cabinet Office flat maps",
    "MPQ": "Privy Council: maps and plans extracted to flat storage",
    "MPQQ": "Privy Council: maps and plans extracted to extra large flat storage",
    "MPR": "RAIL flat maps",
    "MPS": "British Transport Historical Record Office: maps, plans and surveys",
    "MPT": "British Transport Commission: maps and plans extracted to flat storage",
    "MPZ": "Maps and plans extracted from records of various departments",
    "MR": "Maps and plans extracted to rolled storage from various departments",
    "MRC": "Maps and plans extracted to rolled storage from various departments formerly held at the Public Record Office, Chancery Lane",
    "MRQ": "Maps and plans extracted to rolled storage from various departments held at the Public Record Office, Kew",
    "MT": "Ministries of Transport and related bodies",
    "MUN": "Ministry of Munitions and successors",
    "NATS": "Ministry of National Service",
    "NB": "Benefits Agency",
    "NC": "National Lottery Charities Board and the Community Fund",
    "NCC": "National Consumer Council",
    "NDA": "Records of the Nuclear Decommissioning Authority and its predecessors",
    "NDO": "National Debt Office",
    "NE": "Central Council for Education and Training in Social Work",
    "NF": "Registry of Trade Unions and Employers Associations",
    "NG": "National Gallery",
    "NH": "Countryside Council for Wales",
    "NIA": "National Insurance Audit Department",
    "NICO": "National Incomes Commission",
    "NJ": "Office of Manpower Economics",
    "NK": "Department of Trade and Industry (1983-2007)",
    "NL": "Independent Commission on the Voting System",
    "NMM": "National Maritime Museum",
    "NOMS": "National Offender Management Service",
    "NP": "Office of the President of Social Security Appeal Tribunals, Medical Appeal Tribunals and Vaccine Damage Tribunals and Independent Tribunal Service",
    "NPL": "National Physical Laboratory",
    "NR": "Central Rail Users Consultative Committee",
    "NSC": "National Savings Committee, the Post Office Savings Department and the Department for National Savings",
    "NT": "Inquiry into the Matters Arising from the Death of Stephen Lawrence",
    "NV": "Department for Education and Employment",
    "NW": "Interception of Communications Act Commissioner",
    "NX": "Security Service Act Commissioner",
    "NY": "Intelligence Services Act Commissioner",
    "OBS": "Obsolete lists and indexes",
    "OCM": "Ofcom (the Office of Communications)",
    "OD": "Department of Technical Co-operation, and successive Overseas Development bodies",
    "OLD": "Olympic Lottery Distributor",
    "OPG": "Office of the Public Guardian",
    "OS": "Ordnance Survey of Great Britain",
    "OSA": "Office of the Schools Adjudicator",
    "PALA": "Records of the Palace Court",
    "PB": "Teacher Training Agency and Successors",
    "PC": "Privy Council",
    "PCAP": "Judicial Committee of the Privy Council",
    "PCOM": "Prison Commission and Home Office Prison Department",
    "PCGN": "Permanent Committee on Geographic Names",
    "PD": "New Millennium Experience Company",
    "PEV": "Court of the Honour of Peveril",
    "PF": "Department for Culture, Media and Sport",
    "PH": "Central Council for Education and Training in Social Work",
    "PHSO": "Parliamentary and Health Service Ombudsman",
    "PIN": "Ministry of Pensions and National Insurance",
    "PITA": "Inquiry into Human Tissue Analysis in UK Nuclear Facilities (Redfern Inquiry)",
    "PJ": "Department of Trade, 1974-1983",
    "PL": "Palatinate of Lancaster",
    "PMG": "Paymaster General's Office and predecessors",
    "PN": "Inquiry into BSE",
    "POST": "Royal Mail Group plc and predecessors",
    "POWE": "Ministry of Power",
    "PP": "Keeper of the Privy Purse",
    "PREM": "Prime Minister's Office",
    "PRIS": "King's Bench, Fleet, and Marshalsea prisons",
    "PRO": "Domestic Records of the Public Record Office, Gifts, Deposits, Notes and Transcripts",
    "PROB": "Prerogative Court of Canterbury",
    "PSO": "Keeper of the Privy Seal",
    "PT": "Public Trustee Office",
    "PV": "Department of Industry (1974-1983)",
    "PWLB": "Loan Commissioners and the Public Works Loan Board",
    "PX": "Postal Services Commission",
    "PY": "Office of Gas and Electricity Markets (OFGEM)",
    "QAB": "Queen Anne's Bounty",
    "QAPS": "Archive Production Services: material sent off-site for storage",
    "QFA": "Supplementary Finding Aids from The National Archives",
    "QLIB": "Resource Centre and Library stores material sent off-site for storage",
    "QLX": "List and Index Society store material sent off-site for storage",
    "QPR": "Pipe Roll Society stock sent off-site for storage",
    "RAIL": "Pre-nationalisation railway companies, pre-nationalisation canal and related companies",
    "RB": "Adult Learning Inspectorate",
    "RC": "Learning and Skills Council",
    "RD": "Environment Agency",
    "RECO": "Ministry of Reconstruction",
    "REQ": "Court of Requests",
    "RF": "Insolvency Service",
    "RG": "General Register Office, Social Survey Department, and Office of Population Censuses and Surveys",
    "RGO": "Royal Greenwich Observatory",
    "RH": "Department for Children, Schools and Families and Successor",
    "RJ": "Hutton Inquiry",
    "RM": "Royal Botanic Gardens, Kew",
    "RP": "Radio Authority",
    "RS": "Records originally intended for this code are now in JT",
    "RT": "Commission for Africa",
    "RV": "Report of the Committee of Privy Counsellors appointed to consider authorised procedures for the interrogation of persons suspected of terrorism (Parker Inquiry)",
    "RW": "The National Archives",
    "SA": "Commission for Judicial Appointments and Successors",
    "SB": "The Pensions Regulator",
    "SC": "Special Collections: records of various departments, arranged according to type",
    "SCOT": "Scottish Administration",
    "SD": "Zahid Mubarek Inquiry",
    "SE": "Chemical Regulations Directorate",
    "SF": "Statistics Commission",
    "SFO": "Serious Fraud Office",
    "SH": "Equal Opportunities Commission",
    "SJ": "Gas and Electricity Consumer Council (Energywatch)",
    "SK": "Consumer Council for Postal Services (PostWatch)",
    "SL": "Inquests into the deaths of Diana, Princess of Wales, and Emad El-Din Mohamed Abdel Moneim Fayed",
    "SLC": "Student Loans Company Ltd",
    "SO": "Signet Office",
    "SP": "State Paper Office, including papers of the Secretaries of State up to 1782",
    "SR": "Department for Business, Enterprise and Regulatory Reform",
    "ST": "Department for Innovation, Universities and Skills",
    "STAC": "Court of Star Chamber and of other courts",
    "STAT": "Stationery Office",
    "SU": "Department of Energy and Climate Change",
    "SUPP": "Ministry of Supply and successors and the Ordnance Board",
    "SW": "Natural England",
    "T": "HM Treasury",
    "TCB": "Post Office telegraph and telephone service",
    "TCC": "Post Office Corporation (Telecommunications Division)",
    "TCD": "British Telecommunications (public corporation)",
    "TCK": "Private collections of telecommunications related records held by BT Archives",
    "TG": "Tate Gallery",
    "TITH": "Tithe Commission and successors",
    "TR": "Tribunals Service",
    "TS": "Treasury Solicitor and HM Procurator General's Department",
    "TV": "Television Authority and the Independent Broadcasting Authority",
    "UGC": "Higher Education Funding Council for England",
    "UKSC": "The Supreme Court of the United Kingdom",
    "UKTI": "UK Trade & Investment (UKTI)",
    "VC": "The Victoria Climbié Inquiry",
    "VCA": "Vehicle Certification Agency",
    "VL": "Central Veterinary Laboratory and Veterinary Laboratories Agency",
    "VOSA": "Vehicle and Operator Services Agency",
    "WA": "National Assembly for Wales",
    "WALE": "Legal Records Relating to Wales",
    "WARD": "Court of Wards and Liveries",
    "WM": "National Weights and Measures Laboratory",
    "WO": "War Office, Armed Forces, Judge Advocate General, and related bodies",
    "WORK": "Office of Works and successors",
    "ZBOX": "Unfinished and unpublished texts, calendars and finding aids",
    "ZHC": "Publications of the House of Commons",
    "ZHL": "Publications of the House of Lords",
    "ZJ": "London Gazettes",
    "ZLIB": "British Transport Historical Records Office: publications",
    "ZMAP": "Maps and plans formerly held by the Public Record Office Library",
    "ZOS": "Publications of the Ordnance Survey of Great Britain",
    "ZPER": "British Transport Historical Records Office library: periodicals",
    "ZSPC": "British Transport Historical Records Office library: publications",
    "ZWEB": "Regularly Archived Government Websites",
    "Y": "UK Parliament",
    "LITV": "Inquiry into the death of Alexander Litvinenko: Evidence, Correspondence and Report",
    "EDG": "Employment Department, Training Agency",
    "BEIS": "Department for Business, Energy and Industrial Strategy",
    "CHIL": "Iraq Inquiry",
    "DBT": "Department for Business and Trade",
    "DEX": "Department for Exiting the European Union",
    "DIT": "Department for International Trade",
    "ESNZ": "Department for Energy Security and Net Zero",
    "GTI": "Grenfell Tower Inquiry",
    "ICSA": "Independent Inquiry into Child Sexual Abuse",
    "SIT": "Department for Science, Innovation and Technology",
    "YBBK": "The Beaverbrook Papers",
    "YHNN": "Papers of Sir Patrick Joseph Henry Hannon MP (1874-1963)",
    "YFLS": "Papers of Frances Stevenson (1888-1972)",
    "YHEA": "Papers of Timothy Michael Healy, KC",
    "YWAR": "The Wargrave Papers",
    "YBAL": "Papers of Harold Harrington Balfour (1897-1988, 1st Baron Balfour of Inchrye",
    "YBLU": "Papers of Ralph David Blumenfeld",
    "YOWE": "The Owen Papers",
    "YLG": "The Lloyd George Papers",
    "YBLK": "Papers of Robert Norman William Blake (1916-2003, Baron Blake of Braydeston",
    "YDON": "Papers of Sir Robert Donald",
    "YBL": "The Bonar Law Papers",
    "YJCS": "Papers of Sir John Christopher Sainty",
    "YALC": "Papers of the Association of Lord-Lieutenants of Counties",
    "YBAD": "The Ballantine Drawings",
    "YDIX": "Papers of William Lawrence Dixon, Hansard Reporter",
    "YLEM": "Papers of Sir Denis Le Marchant, 1st Baronet, MP (1795-1874)",
    "YKEN": "Drawings from the Kennedy albums",
    "YSTH": "Stow Hill Papers",
    "YPHO": "House of Commons Library Photograph Albums",
    "YWHA": "Baroness Wharton",
    "YBYS": "Roland Boyes",
    "YBIE": "Papers of the Britain in Europe Campaign",
    "YCBP": "Records of Crossbench Peers",
    "YMCL": "Papers of Jean McLintock",
    "YBLY": "Plans and drawings of Henry Bailey, Architect",
    "YDOE": "Records of the Department of the Environment, 1970-1972",
    "YCRI": "Lords and Commons Cricket Club",
    "YSAL": "Salvin Papers",
    "YARC": "Architectural Archive",
    "YLEA": "Personal and family papers of John Temple Leader (1810-1903)",
    "YDCO": "Papers of Arthur Henderson MP on the Disarmament Conference in Geneva, 1932",
    "YCHA": "Records relating to Edmund Lechmere Charlton and the Ludlow Charities Case",
    "YRGR": "Book of Reference relating to Reading, Guildford and Reigate Railway Bill",
    "YMC": "House of Lords Motor Club",
    "YONS": "Papers relating to Arthur Onslow, (1691-1768, Speaker of the House of Commons",
    "YILB": "Papers of Sir Courtenay Ilbert",
    "YRSW": "Papers of Robert Spence Watson",
    "YLEV": "Papers of Benn Wolfe Levy, MP MBE (1900-1973)",
    "YMAS": "Press cutting books of David Marshall Mason (1865-1945, MP",
    "YVUL": "Vulliamy Clock Designs",
    "YMPF": "Minutes of the Parliamentary Farmers' Club",
    "YUAM": "The Unitarian Association Marriage Law Petitioning Papers",
    "YBOND": "The Papers of Maurice Bond (1916-1983) and Shelagh Bond (1926-1973)",
    "YPEE": "The Complete Peerage Trust",
    "YFAR": "'Parliament Past and Present', Farmer Photographs and Glass Plate Negatives Collection",
    "YMER": "The Mersey Manuscripts",
    "YPARL": "Bicameral Records of Parliament",
    "YLYC": "House of Lords Yacht Club",
    "YTAL": "Papers of Sir George John Talbot (1861-1938, Judge",
    "YGUR": "Records of W B Gurney and Sons",
    "YGCA": "Papers of Sir Gilbert Campion (1882-1958)",
    "YRM": "Richard Morgan, House of Lords and House of Commons Computer Officer",
    "YVGO": "Papers of Sir Victor Martin Reeves Goodman",
    "YBNE": "The papers of Baron Braine of Wheatley, 1947-1994",
    "YCHN": "Papers of William Chandler",
    "YDIP": "Papers of William, Lord Diplock",
    "YWDR": "Sir William Drake's Common-Place Book",
    "YMRY": "Lithographs of political figures",
    "YSAS": "Papers of the Houses of Parliament Sports and Social Club",
    "YSLF": "The Papers of John George Shaw Lefevre, 1797-1879",
    "YBOY": "Papers of General Sir Robert Boyd, Governor of Gibraltar",
    "YREI": "The Reid Papers",
    "YMAT": "Letters to Sir Miles Mattinson, MP",
    "YACT": "Miscellaneous prints of acts, ordinances and other documents",
    "YBAI": "Papers of Robert Bailey",
    "YDR": "Papers of David Lockhart-Mure Renton (1908-2007)",
    "YCAD": "Papers of George Henry Cadogan (1840-1915, fifth Earl Cadogan",
    "YLCR": "Personal Papers of Mrs Bessie Le Cras, Parliamentary Agent for Lady Nancy Astor",
    "YDEW": "Papers of David Dewar",
    "YEYT": "Papers of Robert William Eyton (1815-1881)",
    "YHAN": "Hansard Publications and Papers",
    "YBOT": "Papers of Arthur Bottomley",
    "YPRG": "House of Commons Parliamentary Press Gallery Papers",
    "YHL": "Records of the House of Commons; Records of the House of Lords",
    "YMAL": "Papers of Sir Ian Malcolm",
    "YSAM": "Papers of Herbert Louis Samuel (1870-1963, 1st Viscount Samuel",
    "YASG": "Papers of the Association of Secretaries General of Parliaments",
    "YSTA": "Stansgate Collection of Newspaper Cuttings",
    "YPAN": "Papers of Thomas Charles Pannell (1902-1980, MP",
    "YPWO": "Records Created or Inherited by the Parliamentary Works Office",
    "YCRA": "Lord Crathorne",
    "YSLC": "Statute Law Committee Papers",
    "YSC": "Scottish Commissioners for Bridges and Highways",
    "YST": "Papers of William Wedgwood Benn, 1st Viscount Stansgate",
    "YBEA": "Letters from Major AW Beauclerk, MP",
    "YNIC": "Muriel Nichol (1893-1983, Member of Parliament",
    "YMOW": "Records of the Ministry of Works, 1940-1970",
    "YPSA": "Records of the Property Services Agency, 1972-1990",
    "YCOO": "The Papers of Sir Robert Cooke, MP (1930-1987)",
    "YGRE": "Papers of Thomas Greene",
    "YMOU": "Moulton Barrett Album",
    "YHAT": "Papers of John Hatsell (1733-1820, Clerk of the House of Commons",
    "YHAD": "Papers of Leslie Haden Haden-Guest (1877-1960, 1st Baron Haden-Guest of Saling",
    "YWMT": "William and Mary Tercentenary Trust Papers",
    "YERM": "Papers of Thomas Erskine May (1815-1886, Baron Farnborough",
    "YMWT": "Papers of Meredith White Townsend (1857-1911)",
    "YLEE": "Papers of Sir George Lee (1700-1758)",
    "YASQ": "The Asquith Papers",
    "YDER": "Parliamentary diary of Sir Edward Dering and related papers",
    "YWAL": "Papers of Sir Edward Walker (1612-1677)",
    "YCC": "Records of the Clerk of the Crown",
    "YREN": "Correspondence, papers and press cuttings of Major A L Renton, MP",
    "YWMU": "Palace of Westminster Munitions Unit",
    "YRUN": "Scrapbooks of newspaper clippings charting the career of Norah Cecil Runge, OBE (1884-1978)",
    "YWHI": "Papers of Henry Graham White, MP",
    "YTIC": "Tickell Papers",
    "YWHU": "Original Designs by John Whitehurst III",
    "YPRC": "'The Prize Cartoons'",
    "YTAY": "Papers of A. J. P. Taylor (1906-1990)",
    "YMEL": "Papers of Lady Sarah Melville (nee Tugander, secretary to Andrew Bonar Law",
    "YOPA": "Oaths of Prince Albert, Duke of Saxe, Prince of Saxe Coburg and Gotha",
    "YATK": "Papers of James Richard Atkin, Baron Atkin of Aberdovey (1867-1944)",
    "YHRS": "The Papers of Sir Percy Harris",
    "YPIK": "Correspondence to and from Edmund Pike",
    "YSCT": "Records of the Society of Clerks-at-the-Table",
    "YOOW": "Records of the Office of Works, 1378-1940",
    "YLAN": "Duchy of Lancaster Plans",
    "YTOR": "Torrington Papers",
    "YNRC": "Papers of the National Referendum Campaign",
    "YOXF": "Letters patent revoking the Patent of the Earl of Oxford to act as Lord Keeper in the House of Lords",
    "YSPE": "Papers relating to Spencer Perceval (1762-1812)",
    "YBEN": "Papers of the House of Commons Yacht Club",
    "YREL": "Papers of John Relfe",
    "YROY": "Papers of Lord Royle",
    "YAUT": "Autograph volumes",
    "YEGM": "Papers of Sir John Perceval, first Earl of Egmont (1683-1748)",
    "YWLM": "Correspondence and papers of Edward Walmisley, mainly relating to the Taafe peerage claim",
    "YPRS": "Records of the Proportional Representation Society",
    "YBRY": "The Braye Manuscripts",
    "YBUR": "Papers of Edmund Haviland Burke, Member of Parliament for Christchurch, Dorset (1868-1874)",
    "YS": "Papers of Arthur Edward Alexander Shackleton, Baron Shackleton (1911-1994) MP",
    "YJOW": "Correspondence and papers of Sir William Allen Jowitt (1885-1957, Earl Jowitt",
    "YGIL": "Sir Giles Gilbert Scott Architectural Drawings of the House of Commons Rebuild",
    "YPUG": "Papers of AWN Pugin, (1812-1852); Architect",
    "YHAR": "Designs of John Hardman Studios, Birmingham",
    "YABR": "Papers of Louis Arnold Abraham (1893-1983, Principal Clerk of Committees, House of Commons",
    "YDAV": "Papers of John Campbell Davidson MP (1889-1970)",
    "YMET": "Records of the Metropolitan Police",
    "YCOA": "Papers of Sir Edward Feetham Coates, MP",
    "YMAN": "Papers of the Earls of Manchester",
    "YSML": "Papers of Sir Stuart Montagu Samuel, MP, 1st baronet (1856-1926)",
    "YSOR": "Papers of Reginald Sorensen, MP",
    "YWAK": "Papers of John de Vere Loder, 2nd Baron Wakehurst",
    "YELL": "Photographs of Katharine Elliot, Baroness Elliot of Harwood (1903-1994)",
    "YCOW": "The Cowper Books of Standing Orders",
    "YDRE": "The Papers of Basil St George Drennan, Parliamentary Clerk (1903-1976)",
    "YVER": "Letters of Sir Ralph Verney, Bt, Speaker's Secretary 1921-55",
    "YSTO": "Records of Sir Frederick Stovin",
    "YPAR": "Correspondence from John Parker, MP to Philip Fanner and related papers",
    "YHER": "Papers of Margaret Herbison MP",
    "YWLS": "The Willis Papers",
    "YVAC": "Vachers Private Bills",
    "YASH": "Papers of Edward Gibson (1837-1913, 1st Baron Ashbourne, of Ashbourne, County Meath",
    "YDCH": "Daily Chronicle Investment Corporation Ltd",
    "YCPA": "Records of the Commonwealth Parliamentary Association",
    "YGLE": "Papers of James Kitson, 1st Baron Airedale of Gledhow",
    "YWIL": "Willcocks Papers",
    "YECU": "Records of the Chief Usher of the Exchequer",
    "YFOX": "Letters from Charles Richard Fox to Lord John Russell",
    "YAV": "Parliamentary Audio Visual Collection",
    "YFEL": "Correspondence and Papers of Sir Bryan Fell",
    "YHAI": "Papers of William Henry Haines",
    "YMRS": "Papers of John William Morris (1896-1979, Baron Morris of Borth-y-Gest",
    "YBRO": "Papers of Ernest Brown MP (1881-1962)",
    "YBBW": "Papers of Baron Burghclere of Walden",
    "YSPG": "Records of the Study of Parliament Group",
    "YPET": "Petitions",
    "YLGC": "Records of the Lord Great Chamberlain",
    "YCAT": "Papers, photographs, maps and drawings relating to Robert Catesby and the Gunpowder Plot",
    "YRIC": "Rickman Papers",
    "YBAR": "Papers of Sir Charles Barry (1795-1860, Architect",
    "YPUD": "The Pudsey Photograph Collection",
    "YHCT": "Copies of the Journals of the House of Lords",
    "YJAT": "Papers of James Atkinson (fl 1884-1928)",
    "YMOR": "The Morrison-Bell Papers",
    "YLOC": "Papers of Robert Bruce Lockhart",
    "YRCHM": "Photographic Survey of the Houses of Parliament",
    "YBIR": "Designs and working drawings for the rebuilding of the Houses of Parliament",
    "YBRA": "Papers of Henry Bouverie William Brand, 1st Viscount Hampden",
    "YGBP": "Papers of Sir George Smyth Baden-Powell (1847-98, MP",
    "YBRK": "Photographs of drawings of the New Houses of Parliament by William Hayward Brakspear",
    "YROS": "Papers of George Rose, MP (1744-1818)",
    "YLH": "Records of the Leader of the House of Lords",
    "YHC": "Records of the House of Commons",
    "YSTR": "Papers of John St Loe Strachey (1860-1927)",
    "YSAN": "The Sanderson Press Cuttings and Diaries",
    "YGRO": "Papers of Sir Richard Grosvenor, 1st Baronet (1584-1645)",
    "YTOW": "Hayward Townshend's Proceedings of the House of Commons",
    "YMAD": "Papers of RE Maddison",
    "YWHE": "Papers of Sir Michael Wheeler-Booth",
    "YTWN": "Papers of the Marquess Townshend of Raynham Hall",
    "YWB": "Papers of Richard Greville Verney, 19th Lord Willoughby de Broke",
    "YHPT": "Records of the History of Parliament Trust",
    "YMAP": "Records of the Members' and Peers' Staff Association and Predecessor Bodies",
    "YOL": "Records of Paul Flynn MP",
    "YPIC": "House of Lords Record Office: Picture Library",
    "YLAP": "Lords of Appeal Papers",
    "YPWG": "Records of the Parliamentary Group for World Government",
    "YLOW": "Papers of Robert Lowe, Viscount Sherbrooke",
    "YAN": "Papers of Airey Middleton Sheffield Neave (1916-1979)",
    "YABB": "Letters from Charles Abbott and John Henry Abbott to Sir Egerton Brydges",
    "YWHD": "The Whitehead Papers 1826-1953",
    "YPPR": "Parliamentary Processional Roll",
    "YJLE": "Papers of Jennie Lee, MP (1904-1988)",
    "YPAP": "Parliamentary Agents Papers",
    "YGOO": "Papers of Baron Goodman",
    "YBBL": "Beaverbrook Library Papers",
    "YJEF": "Diary of Rt. Hon. Arthur Frederick Jeffreys MP",
    "YBDL": "Papers of Sir Henry John Fanshawe Badeley (1874-1951, Clerk of the Parliaments and Engraver",
    "YHOL": "Papers of John Holms",
    "YBRI": "Papers regarding Bristol Corporation Acts",
    "YBD": "Papers of Sir John Biggs-Davison, MP",
    "YFRA": "The Fraser Papers",
    "YREG": "The Parliamentary Register, 1743-1793",
    "YCSP": "Commons Speeches",
    "YLEG": "Papers relating to William George Gresham Leveson-Gower",
    "YWLL": "Papers of Baron Williams of Ynyshir, Glamorgan",
    "CRAN": "Cranston Inquiry",
}

COLLECTION_CHOICES = tuple(
    (k, f"{k} - {v}") for k, v in sorted(COLLECTION_NAMES.items(), key=lambda x: x[1])
)
