site_name: DS Search Docs
repo_url: https://github.com/nationalarchives/ds-search
dev_addr: 0.0.0.0:65532
theme:
  name: material
  font: false
markdown_extensions:
  - sane_lists
  - toc:
      permalink: true
nav:
  - 'Home': 'index.md'
  - 'Developer guide':
      - 'Project conventions': 'developer-guide/project-conventions.md'
      - 'Contributing code': 'developer-guide/contributing.md'
      - 'Dependency management': 'developer-guide/dependency-management.md'
      - 'Local development gotchas': 'developer-guide/local-development-gotchas.md'
      - 'Backend development': 'developer-guide/backend.md'
      - 'Frontend development': 'developer-guide/frontend.md'