# Extend the default Ruff configuration
extend = "/home/app/ruff.toml"

[lint]
ignore = [
    "B904", # TODO: Re-evaluate after progressive Ruff adoption
    "B006", # TODO: Re-evaluate after progressive Ruff adoption
    "B018", # TODO: Re-evaluate after progressive Ruff adoption
    "F403", # TODO: Re-evaluate after progressive Ruff adoption
    "F401", # TODO: Re-evaluate after progressive Ruff adoption
    "B007", # TODO: Re-evaluate after progressive Ruff adoption
    "B905", # TODO: Re-evaluate after progressive Ruff adoption
]